################################################################################
# \file bsp.mk
#
# \brief
# Define the CY8CEVAL-062S2-CYW955513SDM2WLIPA target.
#
################################################################################
# \copyright
# Copyright 2021-2022 Cypress Semiconductor Corporation
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

# Any additional components to apply when using this board.
# Use a default CM0+ image (CM0P_SLEEP). This can be swapped for a different
# pre-built image or removed if custom built project.
# Use SM for secure mode of CYW55513IUBG chips
BSP_COMPONENTS:=CM0P_SLEEP HCI-UART WIFI_INTERFACE_SDIO SM CYW955513SDM2WLIPA wlbga_iPA_sLNA_ANT0

#Any additional defines to apply when using this board.
BSP_DEFINES:=CY_USING_HAL CYBSP_WIFI_WL_HOSTWAKE_DRIVE_MODE=CYHAL_GPIO_DRIVE_PULLUP CYBSP_WIFI_WL_HOSTWAKE_INIT_STATE=WHD_TRUE CYBSP_WIFI_HOST_WAKE_IRQ_EVENT=CYHAL_GPIO_IRQ_FALL

#Define Default Country code for Wi-Fi Module
BSP_DEFINES+=CY_WIFI_COUNTRY='WHD_COUNTRY_UNITED_STATES'

################################################################################
# ALL ITEMS BELOW THIS POINT ARE AUTO GENERATED BY THE BSP ASSISTANT TOOL.
# DO NOT MODIFY DIRECTLY. CHANGES SHOULD BE MADE THROUGH THE BSP ASSISTANT.
################################################################################

# Board device selection. MPN_LIST tracks what was selected in the BSP Assistant
# All other variables are derived by BSP Assistant based on the MPN_LIST.
MPN_LIST:=CY8C624ABZI-S2D44 CYW55513IUBG
DEVICE:=CY8C624ABZI-S2D44
ADDITIONAL_DEVICES:=CYW55513IUBG
DEVICE_COMPONENTS:=55500 55500A1 CAT1 CAT1A PSOC6_02
DEVICE_CY8C624ABZI-S2D44_CORES:=CORE_NAME_CM0P_0 CORE_NAME_CM4_0
DEVICE_CY8C624ABZI-S2D44_DIE:=PSoC6A2M
DEVICE_CY8C624ABZI-S2D44_FLASH_KB:=2048
DEVICE_CY8C624ABZI-S2D44_SRAM_KB:=1024
DEVICE_CYW55513IUBG_CORES:=CORE_NAME_CM33_0
DEVICE_CYW55513IUBG_DIE:=55500A1
DEVICE_CYW55513IUBG_FLASH_KB:=0
DEVICE_CYW55513IUBG_SRAM_KB:=768
DEVICE_DEFINES:=BLHS_SUPPORT TRXV5
DEVICE_LIST:=CY8C624ABZI-S2D44 CYW55513IUBG
DEVICE_TOOL_IDS:=bsp-assistant bt-configurator capsense-configurator capsense-tuner device-configurator dfuh-tool library-manager lin-configurator ml-configurator project-creator qspi-configurator seglcd-configurator smartio-configurator usbdev-configurator
RECIPE_DIR:=$(SEARCH_recipe-make-cat1a)
